In [1]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [2]:
print(clf.predict([[-0.8, -1]]))

[1]


In [3]:
# get support vectors
clf.support_vectors_

array([[-1., -1.],
       [-2., -1.],
       [ 1.,  1.],
       [ 2.,  1.]])

In [4]:
# get indices of support vectors
clf.support_

array([0, 1, 2, 3])

In [5]:
# get number of support vectors for each class
clf.n_support_ 

array([2, 2])