# V1

In [55]:
import re, math
from collections import Counter

WORD = re.compile(r'\w+')

def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])

     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)

     if not denominator:
        return 0.0
     else:
        return float(numerator) / denominator

def text_to_vector(text):
     words = WORD.findall(text)
     return Counter(words)

text1 = 'i saw the saw'
text2 = 'i saw her standing there'

vector1 = text_to_vector(text1)
vector2 = text_to_vector(text2)

cosine = get_cosine(vector1, vector2)

print 'Cosine:', cosine

Cosine: 0.547722557505


# V2

In [42]:
documents = (
"The sky is blue",
"The sun is bright",
"The sun in the sky is bright",
"We can see the shining sun, the bright sun"
)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

(4, 11)


In [44]:
# tfidf_vectorizer.fit_transform(['The sky is clear'])

In [45]:
tfidf_matrix.toarray()

array([[0.65919112, 0.        , 0.        , 0.        , 0.42075315,
        0.        , 0.        , 0.51971385, 0.        , 0.34399327,
        0.        ],
       [0.        , 0.52210862, 0.        , 0.        , 0.52210862,
        0.        , 0.        , 0.        , 0.52210862, 0.42685801,
        0.        ],
       [0.        , 0.3218464 , 0.        , 0.50423458, 0.3218464 ,
        0.        , 0.        , 0.39754433, 0.3218464 , 0.52626104,
        0.        ],
       [0.        , 0.23910199, 0.37459947, 0.        , 0.        ,
        0.37459947, 0.37459947, 0.        , 0.47820398, 0.39096309,
        0.37459947]])

In [46]:
tfidf_vectorizer.get_feature_names()

[u'blue',
 u'bright',
 u'can',
 u'in',
 u'is',
 u'see',
 u'shining',
 u'sky',
 u'sun',
 u'the',
 u'we']

In [47]:
import pandas as pd
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names())

blue    bright       can        in        is       see   shining  \
0  0.659191  0.000000  0.000000  0.000000  0.420753  0.000000  0.000000   
1  0.000000  0.522109  0.000000  0.000000  0.522109  0.000000  0.000000   
2  0.000000  0.321846  0.000000  0.504235  0.321846  0.000000  0.000000   
3  0.000000  0.239102  0.374599  0.000000  0.000000  0.374599  0.374599   

        sky       sun       the        we  
0  0.519714  0.000000  0.343993  0.000000  
1  0.000000  0.522109  0.426858  0.000000  
2  0.397544  0.321846  0.526261  0.000000  
3  0.000000  0.478204  0.390963  0.374599

In [48]:
cosine_similarity(tfidf_matrix[1:2], tfidf_matrix)

array([[0.36651513, 1.        , 0.72875508, 0.54139736]])

In [49]:
tfidf_matrix[1:1]

<0x11 sparse matrix of type '<type 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [50]:
text = ['i saw the saw', 'i saw her standing there']


In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(text)
print(tfidf_matrix.shape)

(2, 5)


In [52]:
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names())

her       saw  standing       the     there
0  0.000000  0.818180  0.000000  0.574962  0.000000
1  0.534046  0.379978  0.534046  0.000000  0.534046

In [53]:
cosine_similarity(tfidf_matrix[1:2], tfidf_matrix)

array([[0.31089077, 1.        ]])

In [54]:
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)

array([[1.        , 0.31089077]])

In [57]:
import nltk
import sklearn

print('The nltk version is {}.'.format(nltk.__version__))
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The nltk version is 3.2.5.
The scikit-learn version is 0.19.1.
